[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:app]
extends = env
build_src_filter = +<main.cpp>
lib_deps =
  ncmreynolds/ld2410 @ ^0.1.3
  fastled/FastLED @ ^3.7.0

[env:radar_test]
extends = env
build_src_filter = +<radar_test.cpp>
lib_deps = ncmreynolds/ld2410 @ ^0.1.3

[env:led_test]
extends = env
build_src_filter = +<led_test.cpp>
lib_deps = fastled/FastLED @ ^3.7.0